[tool.poetry]
name = "pep440-version-utils"
version = "0.1.0"
description = "Utilities to deal with pep440 versioning"
authors = ["Maxime Verger <me@maxvdb.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.7"
packaging = "^20.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
